### ISSUE TITLE
Add library refresh generated content routine

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-tooling#101]
Add a command to refresh all generated content in a Library.

The publisher currently does this in the CqlSubSystem here:

https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java

The tooling should do the same.

**Comment by jward-123** [comment]
Hey Bryn, love the Akbar image. I'm working on a project that could really use this feature in Atom. Are there some milestones you have in mind for this? I could be wrong, but it doesn't appear to have a final state in current. Thanks!

**Comment by brynrhodes** [comment]
Hi @jward-123 , I've been using the 1.3.1-SNAPSHOT to do this already in several IGs, a recent example is [Lung Cancer Screening](https://github.com/cqframework/lcs-cds). So if you use the _refresh and _updateCQFTooling scripts from there, it should work with the 1.3.1-SNAPSHOT.

**Comment by jward-123** [comment]
Thanks Bryn! This looks great for LCS. Is there step list or readme somewhere that lays out the important folders to specify dependencies under? ( included libraries mainly ). I can see FHIRCommon being included, but I don't see how the tool knows to look in the CQL folder for the file itself. Is it just something that's stored in the cache as part of the _refresh and _updateCQFTooling scripts? Also, do namespaces work? E.g.  include MyName.MyLibrary version '4.0.1' called lib

**Comment by brynrhodes** [comment]
There is a [Sample Content IG](https://github.com/cqframework/sample-content-ig) that sets up the basic patterns, and if you open an Atom editor on the root of a repository, the CQL authoring features are available based on the folder structure commonly used in FHIR implementation guides.

**Comment by jward-123** [comment]
Hey Bryn,

We had trouble getting this to work with our system so we're currently running the project through the command line. In accordance with the license I'm replying here to let you know we've added a line to the cql-to-elm.bat file to wait for a user key press before exiting for usability reasons. This is only in our local copy.

**Comment by Chris0296** [comment]
Closing. This functionality has been implemented in the referenced PRs. 

If there are problems related to use of this functionality please open a new issue.
