### ISSUE TITLE
IG Refresh Tooling

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-tooling#28]
Definition of done: The tooling supports being added to the genonce for an IG project and that automatically regenerates narrative for all knowledge resources (including PlanDefinitions and ActivityDefinitions), adds/sets publishing metadata for all conformance and knowledge resources, bundles test cases, and bundles packaging artifacts, and the results of all that are included in the published IG.

**Comment by c-schuler** [comment]
This has been implemented
