### ISSUE TITLE
CMS 104 does not have expected data requirements output

### ISSUE THREAD

**Issue by TychonautVII** [cqframework/cqf-tooling#309]
**Describe the bug**

In the tests in src/test/java/org/opencds/cqf/tooling/utilities/ECQMCreatorIT.java
The data requirements operation ran against the CMS 104 is missing an expected data requirement of "Encouter" 

On this "branch feature-cms104_investigation" I've updated the CMS 104 test to cause it to fail, see the code here.

https://github.com/cqframework/cqf-tooling/pull/308/files#r743845079

**To Reproduce**
Run the CMS 104 Test in In the tests in src/test/java/org/opencds/cqf/tooling/utilities/ECQMCreatorIT.java on the branch "branch feature-cms104_investigation" (unless that branch as been moved) 

**Expected behavior**
At a minimum, we expect this measure to have a data requirement of the "Encounter" FHIR resource

**Comment by brynrhodes** [comment]
Included in 1.4.1
