### ISSUE TITLE
Add "name" to the effective data requirements library

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-tooling#348]
The result of an effective data requirements calculation is a module definition library. As a Library resource, it is subject to the lib-0 constraint on name defined in the base resource, which requires that the name element be usable as a machine-processable identifier. Set the "name" element of the resulting module definition library to "EffectiveDataRequirements" to satisfy this constraint.

**Comment by c-schuler** [comment]
This change will go into the clinical_quality_language repository and updated here once resolved

**Comment by JPercival** [comment]
Resolved by https://github.com/cqframework/clinical_quality_language/pull/1214
