### ISSUE TITLE
Libraries generated as part of Refresh should NOT have an ID value with the "library-" prefix

### ISSUE THREAD

**Issue by sliver007** [cqframework/cqf-tooling#350]
**Describe the bug**
When a FHIR Library is generated as part of the Refresh Operation, the ID of that generated Library should NOT include the "library-" prefix.

**To Reproduce**

1. Create a new CQL Library for which a FHIR Library does not exist in the IG
2. Run the RefreshIG operation
3. A corresponding FHIR Library will be generated, note that its ID value includes the "library-" prefix

**Expected behavior**
In the scenario described above, the generated FHIR Library's ID value should NOT include the "library-" prefix

**Comment by brynrhodes** [comment]
Included in 1.4.1
