### ISSUE TITLE
PrimaryCodePath for ServiceRequest is incorrect

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-tooling#404]
PrimaryCodePath for ServiceRequest and ServiceNotRequested is "type", is should be "code".

**Comment by Chris0296** [comment]
This appears to have been fixed here: https://github.com/cqframework/cqf-tooling/pull/400

Can we close this? @brynrhodes @c-schuler

**Comment by Chris0296** [comment]
Resolved in #400
