### ISSUE TITLE
Date roller tooling does not handle the case when prefetch data is included in a test cases

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-tooling#408]
Date roller expects the old format for prefetch data of request/response, update to handle that case, as well as the case where the bundle and/or resources are included directly in the prefetch key.

**Comment by bryantaustin13** [comment]
https://github.com/cqframework/cqf-tooling/pull/409#issue-1497277340

**Comment by c-schuler** [comment]
Resolved in #409 & #423
