### ISSUE TITLE
Refresh IG fails on case-sensitive operating systems

### ISSUE THREAD

**Issue by JPercival** [cqframework/cqf-tooling#42]
If the IG has a structure such as:

input/resources/Library

instead of:

input/resources/library

It will fail to refresh. To repro:

1. check out the Opioid cds ig on mac or linux
2. Rename the library folder to Library
3. Run the refresh

**Comment by Chris0296** [comment]
I have tested this in opioid-cds-r4 ig, and did not encounter this issue. This repo uses a newer version (2.1.0) of the tooling which has resolved this issue.
