### ISSUE TITLE
Add short, definition, and comment content to ModelInfo

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cqf-tooling#52]
Add support for text descriptions of the elements, pull from the short, definition, and comment elements of the StructureDefinition.

**Comment by brynrhodes** [comment]
Related to CQL-to-ELM translator issue [503](https://github.com/cqframework/clinical_quality_language/issues/503)

Specifically, support:
label - A string user-friendly label for the element
definition - A markdown definition of the element
comment - A markdown comment for the element
bindingStrength - required,extensible,preferred,example
bindingValueSet - url of a value set specifying possible values
constraint - ConstraintInfo { name, severity (error|warning), expression (CQL w/o retrieves, parameterized by Value of the type of the element), message }
mustSupport - A Boolean indicator of mustSupport

**Comment by brynrhodes** [comment]
In addition, investigate the fact that "enumerated" types derive directly from Element instead of the more specific type (e.g. AddressUse derives from Element, but should it derive from FHIR.code)?
Also investigate types in QICore that are deriving from a choice (e.g. abatement in QICore)

**Comment by Chris0296** [comment]
Closing. Functionality has been implemented.
