### ISSUE TITLE
Break existing implementation into separate operations

### ISSUE THREAD

**Issue by SeanWheelwright** [cqframework/cqf-tooling#59]
Includes creating operations and exposing argument processors for each of these:

Refresh generated content
Refresh Publication data
Validate everything is correct
Package
Deploy

**Comment by Chris0296** [comment]
A 'RefreshGeneratedContentOperation' has been added to the repository since this issue was opened. 

Given the age of this ticket and limited information provided, we will close it. If there is desire to pursue additional changes related to this matter please open a new issue.
