### ISSUE TITLE
Implement templating 

### ISSUE THREAD

**Issue by SeanWheelwright** [cqframework/cqf-tooling#60]
Ensure everything exists and create as much of things that don’t as possible

- JSON resources that are parameterized
     - Measure, PlanDefinition, ActivityDefinition, Test Case
         - Directory, Patient resource, ExpectedResult (MeasureReport resource
- Atom plugin exists for this?

**Comment by Chris0296** [comment]
Given the age and lack of information provided in this issue, we will close it. 

If there is a desire to pursue this functionality, please open a new ticket and provide additional information on what is expected and the problems it will resolve.
