### ISSUE TITLE
Add documentation about mvn settings.xml

### ISSUE THREAD

**Issue by p9g** [cqframework/cqf-tooling#9]
I needed to create %USERPROFILE%\.m2\settings.xml with the following to get the tool to work

	<profiles>
		<profile>
			<id>oss.sonatype.org-snapshot</id>
			<repositories>
				<repository>
					<id>oss.sonatype.org-snapshot</id>
					<url>https://oss.sonatype.org/content/repositories/snapshots</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
			</repositories>
		</profile>
	</profiles>
	<activeProfiles>
		<activeProfile>oss.sonatype.org-snapshot</activeProfile>
	</activeProfiles>

Suggest adding some documentation about mvn configuration.

**Comment by JPercival** [comment]
Resolved by #46
