### ISSUE TITLE
Tooling requires included library files to be named using their version number

### ISSUE THREAD

**Issue by mholck** [cqframework/cqf-tooling#96]
Currently the tooling requires the included libraries to be named with name and version such as Hospice-2.0.000. If we remove the version numbers from the filenames it breaks when refreshing and bundling the measures

4 included cql Libraries not found: 
Hospice-2.0.000 MISSING
AdultOutpatientEncounters-2.0.000 MISSING
MATGlobalCommonFunctions-5.0.000 MISSING
SupplementalDataElements-2.0.0 MISSING

We should be able to name the libraries without their version number embedded in the filename. For backward compatibility we might want to look for the library without version number and if found use it. If not found then look for the library with the version number.

**Comment by brynrhodes** [comment]
Pursuing this further, we want the tooling to support versioning as part of bundling.
So for the purposes of version history tracking, canonical URLs (and therefore _names_) should not include any part of the version. But when we package a measure, the ids of the resources in the bundle should include the version. (The alternative would be to put that on the ingesting server).

So next steps for this issue are:
1) In the ecqm-content-r4, put only 2019 measure content and get it to a publishable state.
2) Cut a release
3) Create a branch for 2020 measure content and update/add content there.
4) Ensure that the tooling supports packaging and publishing for both branches.

**Comment by c-schuler** [comment]
Resolved in #148
